### ISSUE TITLE
Add a Rocket Icon instead of rectangle figure 

### ISSUE THREAD

**Issue by Ankursehrawat15** [Ankursehrawat15/SpaceDodge#1]
In game play there is a simple rectangle drawn. Instead there should be rocket image.
![Screenshot 2023-03-10 at 1 42 29 PM](https://user-images.githubusercontent.com/61679890/224260231-f6c6373c-b08b-4029-a36e-07dd74d54af2.png)

**Comment by Omppu42** [comment]
I can look at this.

**Comment by Ankursehrawat15** [comment]
Issue is solved. Thanks @Omppu42
